import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, ChevronRight, CircleUserRound, Clock3, House, Menu, Music2, Search, Settings, SlidersHorizontal, Star, Ticket, UserRound, X } from 'lucide-react';
import './styles.css';

const places = [
  { name: '한울교회', meta: '경기도 남양주시 · 최대 150명', rating: '4.8', image: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=500&q=80' },
  { name: '망원동 카페 웨이브', meta: '서울 마포구 · 최대 50명', rating: '4.6', image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=500&q=80' },
  { name: '이음 문화센터', meta: '서울 성동구 · 최대 80명', rating: '4.9', image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=500&q=80' },
];
const shows = [
  { title: '술탄 오브 더 디스코', date: '10/24–10/25', place: '경기도 시흥 시흥교회', category: 'Music', progress: 82, image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=700&q=80' },
  { title: 'Pocket Music Fest', date: '10.03 (토) · 18:00', place: '한울교회 · 30석', category: 'Music', progress: 64, image: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=700&q=80' },
  { title: 'Oasis concert', date: '12/02–12/15', place: '망원동 카페 웨이브', category: 'Lo-fi', progress: 47, image: 'https://images.unsplash.com/photo-1521337581100-8ca9a73a5f79?auto=format&fit=crop&w=700&q=80' },
  { title: 'Indie Band Bon', date: '11/24–12/1', place: '서울 성동구', category: 'Band', progress: 71, image: 'https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=700&q=80' },
];
const categories = ['All', 'Music', 'Band', 'Lo-fi', 'Jazz'];

function Rating({ value = '4.8' }) { return <span className="rating"><Star size={12} fill="currentColor" /> {value}</span>; }
function TopBar({ action }) { return <div className="topbar"><button className="icon-btn"><Menu size={20} /></button><div className="logo">C<span>r</span>oc</div><div className="top-actions"><button className="icon-btn"><Bell size={18} /></button><button onClick={action} className="icon-btn"><CircleUserRound size={18} /></button></div></div>; }
function SearchBox({ value, onChange, placeholder='Searching...' }) { return <div className="search-box"><Search size={16} /><input value={value} onChange={e => onChange?.(e.target.value)} placeholder={placeholder} /></div>; }
function SectionTitle({ children, onClick }) { return <div className="section-title"><h2>{children}</h2><button onClick={onClick}>see all <ChevronRight size={14}/></button></div>; }
function Home({ go }) {
  const [query, setQuery] = useState('');
  return <div className="page home-page"><div className="hero"><TopBar action={() => go('mypage')} /><div className="hero-copy"><p>Find your stage</p><h1>무대 위<br/>스타를<br/>우리 집 앞으로</h1><div className="music-notes">♫</div></div><SearchBox value={query} onChange={setQuery} /></div><main className="content">
    <SectionTitle onClick={() => go('places')}>Recommend</SectionTitle><div className="recommend-card" onClick={() => go('places')}><img src={places[0].image}/><div><strong>{places[0].name}</strong><p>{places[0].meta}</p><Rating value={places[0].rating}/></div><ChevronRight size={18}/></div>
    <SectionTitle onClick={() => go('places')}>Place</SectionTitle><div className="place-row">{places.map(p => <button className="place-card" key={p.name} onClick={() => go('places')}><img src={p.image}/><strong>{p.name}</strong><small>{p.meta.split(' · ')[0]}</small><Rating value={p.rating}/></button>)}</div>
    <SectionTitle onClick={() => go('shows')}>Categories</SectionTitle><div className="category-row">{categories.slice(1).map(c => <button key={c} onClick={() => go('shows')}>{c}</button>)}</div>
  </main></div>;
}
function ShowCard({ show, onClick }) { return <button className="show-card" onClick={onClick}><img src={show.image}/><div className="show-card-body"><div className="show-title"><strong>{show.title}</strong><Rating value="5.0"/></div><p>{show.date}</p><small>{show.place}</small><div className="funding"><span><b>{show.progress}%</b> funded</span><span>target 30 tickets</span></div><div className="progress"><i style={{width: `${show.progress}%`}}/></div></div></button>; }
function Shows({ go }) {
  const [query, setQuery] = useState(''); const [active, setActive] = useState('All');
  const filtered = useMemo(() => shows.filter(s => (active === 'All' || s.category === active) && s.title.toLowerCase().includes(query.toLowerCase())), [active, query]);
  return <div className="page peach-page"><header className="plain-header"><TopBar action={() => go('mypage')} /></header><main className="content shows-content"><SearchBox value={query} onChange={setQuery} /><div className="chips">{categories.map(c => <button className={active === c ? 'active' : ''} key={c} onClick={() => setActive(c)}>#{c === 'All' ? '추천순' : c}</button>)}<button className="filter"><SlidersHorizontal size={15}/></button></div><SectionTitle>Recommend</SectionTitle><div className="show-grid">{filtered.map(s => <ShowCard key={s.title} show={s} onClick={() => go('detail', s)}/>)}</div>{filtered.length === 0 && <div className="empty">검색 결과가 없어요.<br/>다른 키워드로 찾아보세요.</div>}</main></div>;
}
function MyPage({ go }) { return <div className="page peach-page"><header className="plain-header"><TopBar action={() => {}} /></header><main className="content my-content"><div className="profile"><div className="avatar"><UserRound size={27}/></div><div><h1>김철희님, 안녕하세요!</h1><p>오늘도 가장 가까운 무대를 찾아보세요.</p></div><button className="icon-btn"><Settings size={18}/></button></div><div className="stats"><div><b>1</b><span>에티켓</span></div><div><b>4</b><span>내 공연</span></div><div><b>1</b><span>진행 중 공연</span></div></div><SectionTitle>My ticket</SectionTitle><button className="ticket-card" onClick={() => go('detail', shows[1])}><div className="ticket-art"><Music2 size={27}/><span>Music<br/><b>FEST</b></span></div><div><small>예매 완료</small><strong>Pocket Music Fest</strong><p>10.03 (토) · 18:00<br/>한울교회 · 30석</p></div><span className="ticket-button">티켓 보기</span></button><SectionTitle>My space</SectionTitle><button className="my-space" onClick={() => go('places')}><img src={places[0].image}/><div><small>운영 중</small><strong>호평주 평화 교회</strong><p>남양주시 · 최대 150명</p></div><ChevronRight size={17}/></button><SectionTitle>Show edit</SectionTitle><button className="edit-row" onClick={() => go('create')}><span className="music-icon"><Music2 size={18}/></span><div><strong>우리 동네 뮤지션 나눔</strong><small>뮤지션 · 공연 정보를 등록해보세요</small></div><ChevronRight size={17}/></button></main></div>; }
function Places({ go }) { return <div className="page peach-page"><header className="plain-header"><TopBar action={() => go('mypage')} /></header><main className="content list-page"><div className="list-heading"><div><p className="eyebrow">CrocTick places</p><h1>공간을 고르고<br/>공연을 시작해요</h1></div><button className="icon-btn"><SlidersHorizontal size={18}/></button></div><SearchBox placeholder="지역, 공간 이름 검색"/><div className="place-list">{places.map(p => <button key={p.name} className="large-place" onClick={() => go('detail', {title:p.name, image:p.image, date:'공간 대관 가능', place:p.meta, category:'Place', progress:100})}><img src={p.image}/><div><strong>{p.name}</strong><p>{p.meta}</p><Rating value={p.rating}/><small><Clock3 size={12}/> 평일 대관 가능</small></div><ChevronRight size={18}/></button>)}</div></main></div>; }
function Detail({ show, go }) { const [joined, setJoined] = useState(false); return <div className="page detail-page"><div className="detail-image" style={{backgroundImage:`url(${show.image})`}}><button className="back-btn" onClick={() => go('shows')}>‹</button></div><main className="detail-panel"><div className="detail-head"><span className="pill">{show.category}</span><Rating value="5.0"/></div><h1>{show.title}</h1><p className="muted">{show.date}<br/>{show.place}</p><div className="funding-box"><div><strong>펀딩 달성률</strong><b>{show.progress}%</b></div><div className="progress"><i style={{width:`${show.progress}%`}}/></div><small>목표 달성 시 공연이 확정돼요 · 목표 30명</small></div><h3>이런 공연이에요</h3><p className="description">좋아하는 아티스트의 무대를 우리 동네에서 만나요. 관객의 사전 티켓 구매로 공연이 만들어지고, 목표를 달성하면 공연이 확정됩니다.</p><button className={`primary-btn ${joined ? 'joined' : ''}`} onClick={() => setJoined(true)}>{joined ? '참여 완료! 티켓을 확인하세요' : '티켓 펀딩 참여하기 · 15,000원'}</button></main></div>; }
function Create({ go }) { const [submitted,setSubmitted] = useState(false); return <div className="page peach-page"><header className="plain-header"><TopBar action={() => go('mypage')} /></header><main className="content create-page"><p className="eyebrow">New show</p><h1>우리 동네에서<br/>공연을 열어보세요</h1><label>공연 제목<input placeholder="예: 주말의 작은 콘서트" /></label><label>공연할 공간<select><option>한울교회</option><option>망원동 카페 웨이브</option></select></label><label>티켓 가격<input defaultValue="15,000" /></label><label>목표 관객 수<input defaultValue="30" /></label><button className="primary-btn" onClick={() => setSubmitted(true)}>{submitted ? '공연이 등록됐어요!' : '공연 등록하기'}</button></main></div>; }
function Nav({ active, go }) { return <nav className="bottom-nav"><button className={active === 'home' ? 'selected' : ''} onClick={() => go('home')}><House size={19}/><span>홈</span></button><button className={active === 'shows' ? 'selected' : ''} onClick={() => go('shows')}><Ticket size={19}/><span>공연</span></button><button className={active === 'mypage' ? 'selected' : ''} onClick={() => go('mypage')}><UserRound size={19}/><span>마이</span></button></nav>; }
function App() { const [screen,setScreen] = useState('home'); const [selected,setSelected] = useState(shows[0]); const go = (next,data) => { if(data) setSelected(data); setScreen(next); window.scrollTo({top:0,behavior:'smooth'}); }; const base = screen === 'home' ? 'home' : screen === 'mypage' || screen === 'create' || screen === 'places' ? 'mypage' : 'shows'; return <><div className="phone-shell">{screen === 'home' && <Home go={go}/>} {screen === 'shows' && <Shows go={go}/>} {screen === 'mypage' && <MyPage go={go}/>} {screen === 'places' && <Places go={go}/>} {screen === 'detail' && <Detail show={selected} go={go}/>} {screen === 'create' && <Create go={go}/>} {screen !== 'detail' && <Nav active={base} go={go}/>}</div></>; }
createRoot(document.getElementById('root')).render(<App/>);
